require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TodotasksController do

  # This should return the minimal set of attributes required to create a valid
  # Todotask. As you add validations to Todotask, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TodotasksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all todotasks as @todotasks" do
      todotask = Todotask.create! valid_attributes
      get :index, {}, valid_session
      assigns(:todotasks).should eq([todotask])
    end
  end

  describe "GET show" do
    it "assigns the requested todotask as @todotask" do
      todotask = Todotask.create! valid_attributes
      get :show, {:id => todotask.to_param}, valid_session
      assigns(:todotask).should eq(todotask)
    end
  end

  describe "GET new" do
    it "assigns a new todotask as @todotask" do
      get :new, {}, valid_session
      assigns(:todotask).should be_a_new(Todotask)
    end
  end

  describe "GET edit" do
    it "assigns the requested todotask as @todotask" do
      todotask = Todotask.create! valid_attributes
      get :edit, {:id => todotask.to_param}, valid_session
      assigns(:todotask).should eq(todotask)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Todotask" do
        expect {
          post :create, {:todotask => valid_attributes}, valid_session
        }.to change(Todotask, :count).by(1)
      end

      it "assigns a newly created todotask as @todotask" do
        post :create, {:todotask => valid_attributes}, valid_session
        assigns(:todotask).should be_a(Todotask)
        assigns(:todotask).should be_persisted
      end

      it "redirects to the created todotask" do
        post :create, {:todotask => valid_attributes}, valid_session
        response.should redirect_to(Todotask.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved todotask as @todotask" do
        # Trigger the behavior that occurs when invalid params are submitted
        Todotask.any_instance.stub(:save).and_return(false)
        post :create, {:todotask => {}}, valid_session
        assigns(:todotask).should be_a_new(Todotask)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Todotask.any_instance.stub(:save).and_return(false)
        post :create, {:todotask => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested todotask" do
        todotask = Todotask.create! valid_attributes
        # Assuming there are no other todotasks in the database, this
        # specifies that the Todotask created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Todotask.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => todotask.to_param, :todotask => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested todotask as @todotask" do
        todotask = Todotask.create! valid_attributes
        put :update, {:id => todotask.to_param, :todotask => valid_attributes}, valid_session
        assigns(:todotask).should eq(todotask)
      end

      it "redirects to the todotask" do
        todotask = Todotask.create! valid_attributes
        put :update, {:id => todotask.to_param, :todotask => valid_attributes}, valid_session
        response.should redirect_to(todotask)
      end
    end

    describe "with invalid params" do
      it "assigns the todotask as @todotask" do
        todotask = Todotask.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Todotask.any_instance.stub(:save).and_return(false)
        put :update, {:id => todotask.to_param, :todotask => {}}, valid_session
        assigns(:todotask).should eq(todotask)
      end

      it "re-renders the 'edit' template" do
        todotask = Todotask.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Todotask.any_instance.stub(:save).and_return(false)
        put :update, {:id => todotask.to_param, :todotask => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested todotask" do
      todotask = Todotask.create! valid_attributes
      expect {
        delete :destroy, {:id => todotask.to_param}, valid_session
      }.to change(Todotask, :count).by(-1)
    end

    it "redirects to the todotasks list" do
      todotask = Todotask.create! valid_attributes
      delete :destroy, {:id => todotask.to_param}, valid_session
      response.should redirect_to(todotasks_url)
    end
  end

end
